/**
 * Weapon definitions mimicking the classic Soldat arsenal.
 */
export interface WeaponDef {
    name: string;
    fireRate: number;       // ms between shots
    bulletSpeed: number;    // pixels per frame
    bulletCount: number;    // bullets per shot (>1 for shotgun)
    spread: number;         // radians of random spread
    recoilForce: number;    // force applied to player on fire
    damage: number;         // damage per bullet
    bulletGravity: number;  // gravity applied to bullet per frame
    magazineSize: number;   // bullets before reload
    reloadTime: number;     // ms to reload
    bulletLifetime: number; // frames before bullet despawns
    automatic: boolean;     // hold to keep firing?
    bulletTrailColor: string;
    muzzleFlashColor: string;
    type: 'primary' | 'secondary';
    requiresCharge?: boolean;
    chargeTime?: number; // frames
}

export const WEAPONS: WeaponDef[] = [
    // --- PRIMARIES ---
    {
        name: 'Desert Eagles',
        fireRate: 200,
        bulletSpeed: 28,
        bulletCount: 2, // Dual wielded
        spread: 0.04,
        recoilForce: 4.5,
        damage: 33,
        bulletGravity: 0.04,
        magazineSize: 7,
        reloadTime: 1200,
        bulletLifetime: 500, // Very long range
        automatic: false,
        bulletTrailColor: '#ffdd44',
        muzzleFlashColor: '#ffaa00',
        type: 'primary',
    },
    {
        name: 'HK MP5',
        fireRate: 60,
        bulletSpeed: 26,
        bulletCount: 1,
        spread: 0.05,
        recoilForce: 1.2,
        damage: 12,
        bulletGravity: 0.03,
        magazineSize: 30,
        reloadTime: 1600,
        bulletLifetime: 300,
        automatic: true,
        bulletTrailColor: '#ffee66',
        muzzleFlashColor: '#ff8800',
        type: 'primary',
    },
    {
        name: 'Ak-74',
        fireRate: 90,
        bulletSpeed: 30,
        bulletCount: 1,
        spread: 0.04,
        recoilForce: 2.0,
        damage: 18,
        bulletGravity: 0.03,
        magazineSize: 40,
        reloadTime: 1800,
        bulletLifetime: 400,
        automatic: true,
        bulletTrailColor: '#ffcc33',
        muzzleFlashColor: '#ff6600',
        type: 'primary',
    },
    {
        name: 'Steyr AUG',
        fireRate: 80,
        bulletSpeed: 32,
        bulletCount: 1,
        spread: 0.03,
        recoilForce: 1.8,
        damage: 20,
        bulletGravity: 0.03,
        magazineSize: 30,
        reloadTime: 1700,
        bulletLifetime: 400,
        automatic: true,
        bulletTrailColor: '#ccff33',
        muzzleFlashColor: '#ffcc00',
        type: 'primary',
    },
    {
        name: 'Spas-12',
        fireRate: 350,
        bulletSpeed: 24,
        bulletCount: 6,
        spread: 0.12,
        recoilForce: 6.0,
        damage: 16,
        bulletGravity: 0.06,
        magazineSize: 7,
        reloadTime: 2000,
        bulletLifetime: 100,
        automatic: false,
        bulletTrailColor: '#ddaa33',
        muzzleFlashColor: '#ff9900',
        type: 'primary',
    },
    {
        name: 'Ruger 77',
        fireRate: 800,
        bulletSpeed: 45,
        bulletCount: 1,
        spread: 0.01,
        recoilForce: 7.0,
        damage: 85,
        bulletGravity: 0.02,
        magazineSize: 5,
        reloadTime: 2000,
        bulletLifetime: 600,
        automatic: false,
        bulletTrailColor: '#ffffff',
        muzzleFlashColor: '#ffffff',
        type: 'primary',
    },
    {
        name: 'M79',
        fireRate: 1500,
        bulletSpeed: 18,
        bulletCount: 1,
        spread: 0.02,
        recoilForce: 8.0,
        damage: 120,
        bulletGravity: 0.3,
        magazineSize: 1,
        reloadTime: 2500,
        bulletLifetime: 400,
        automatic: false,
        bulletTrailColor: '#ffbb22',
        muzzleFlashColor: '#ffaa00',
        type: 'primary',
        requiresCharge: true,
        chargeTime: 40,
    },
    {
        name: 'Barrett M82A1',
        fireRate: 1200,
        bulletSpeed: 55,
        bulletCount: 1,
        spread: 0.005,
        recoilForce: 12.0,
        damage: 100,
        bulletGravity: 0.01,
        magazineSize: 10,
        reloadTime: 2200,
        bulletLifetime: 800,
        automatic: false,
        bulletTrailColor: '#ff4444',
        muzzleFlashColor: '#ff2200',
        type: 'primary',
        requiresCharge: true,
        chargeTime: 60, // 1 second
    },
    {
        name: 'FN Minimi',
        fireRate: 50,
        bulletSpeed: 27,
        bulletCount: 1,
        spread: 0.08,
        recoilForce: 1.2,
        damage: 10,
        bulletGravity: 0.04,
        magazineSize: 50,
        reloadTime: 3000,
        bulletLifetime: 300,
        automatic: true,
        bulletTrailColor: '#ccffdd',
        muzzleFlashColor: '#ffdd00',
        type: 'primary',
    },
    {
        name: 'XM214 Minigun',
        fireRate: 30,
        bulletSpeed: 28,
        bulletCount: 1,
        spread: 0.18,
        recoilForce: 0.8,
        damage: 8,
        bulletGravity: 0.05,
        magazineSize: 100,
        reloadTime: 4000,
        bulletLifetime: 200,
        automatic: true,
        bulletTrailColor: '#ffff00',
        muzzleFlashColor: '#ff8800',
        type: 'primary',
    },
    // --- SECONDARIES ---
    {
        name: 'USSOCOM',
        fireRate: 150,
        bulletSpeed: 25,
        bulletCount: 1,
        spread: 0.03,
        recoilForce: 2.5,
        damage: 25,
        bulletGravity: 0.04,
        magazineSize: 12,
        reloadTime: 1000,
        bulletLifetime: 400,
        automatic: false,
        bulletTrailColor: '#aabbff',
        muzzleFlashColor: '#ffffff',
        type: 'secondary',
    },
    {
        name: 'Combat Knife',
        fireRate: 250,
        bulletSpeed: 10,
        bulletCount: 1,
        spread: 0.01,
        recoilForce: 0,
        damage: 80,
        bulletGravity: 0,
        magazineSize: 1,
        reloadTime: 100,
        bulletLifetime: 4,
        automatic: false,
        bulletTrailColor: 'transparent',
        muzzleFlashColor: 'transparent',
        type: 'secondary',
    },
    {
        name: 'Chainsaw',
        fireRate: 30,
        bulletSpeed: 8,
        bulletCount: 3,
        spread: 0.3,
        recoilForce: 0,
        damage: 5,
        bulletGravity: 0,
        magazineSize: 1000,
        reloadTime: 0,
        bulletLifetime: 5,
        automatic: true,
        bulletTrailColor: 'transparent',
        muzzleFlashColor: 'transparent',
        type: 'secondary',
    },
    {
        name: 'M72 LAW',
        fireRate: 3000,
        bulletSpeed: 60,
        bulletCount: 1,
        spread: 0.001,
        recoilForce: 20.0,
        damage: 250,
        bulletGravity: 0,
        magazineSize: 1,
        reloadTime: 5000,
        bulletLifetime: 2000,
        automatic: false,
        bulletTrailColor: '#ffaa00',
        muzzleFlashColor: '#ff3300',
        type: 'secondary',
        requiresCharge: true,
        chargeTime: 120, // 2 seconds of preparation
    },
];


